version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2023.05.1
    steps:
      - checkout
      - restore_cache:
          key: android-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Descargar dependencias
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: android-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Instalar NDK
          command: |
            echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;25.0.8775105"
      - run:
          name: Compilar proyecto
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release
          destination: apks

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
  
